USE [master]
GO

/****** Object:  Database [Kursi]    Script Date: 26.02.2022 22:58:28 ******/
CREATE DATABASE [Kursi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Загадка', FILENAME = N'C:\Users\asya1\Desktop\MSSQL15.SQLEXPRESS\MSSQL\DATA\Загадка.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Загадка_log', FILENAME = N'C:\Users\asya1\Desktop\MSSQL15.SQLEXPRESS\MSSQL\DATA\Загадка_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Kursi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Kursi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Kursi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Kursi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Kursi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Kursi] SET ARITHABORT OFF 
GO

ALTER DATABASE [Kursi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Kursi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Kursi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Kursi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Kursi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Kursi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Kursi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Kursi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Kursi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Kursi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Kursi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Kursi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Kursi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Kursi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Kursi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Kursi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Kursi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Kursi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Kursi] SET  MULTI_USER 
GO

ALTER DATABASE [Kursi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Kursi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Kursi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Kursi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Kursi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Kursi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Kursi] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Kursi] SET  READ_WRITE 
GO


